[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
context-spore = "0.0"
log = "0.4"

[build-dependencies]
bindgen.workspace = true
build-script-cfg.workspace = true
search-mx-tools = { version = "0.0", path = "../search-mx-tools" }